include:
  - docker-compose.opensearch.${OPENSEARCH_CLUSTER_TYPE:-single-node}.yml

services:
  ai:
    profiles:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1gb
    cpus: 2
    command: ./scripts/run-django-dev.sh
    stdin_open: true
    tty: true
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - django_media:/var/media

  celery:
    profiles:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A main.celery:app worker -E -Q default,edx_content -B -l ${MITOL_LOG_LEVEL:-INFO}'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - django_media:/var/media
