model_list:
  - model_name: "*"
    litellm_params:
      model: openai/*
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  # The following should set default customer budgets, but they are
  # being ignored or not created (not sure which).
  # https://docs.litellm.ai/docs/proxy/users
  max_end_user_budget: os.environ/OPENAI_AI_MAX_BUDGET
  max_end_user_budget_duration: os.environ/OPENAI_AI_MAX_BUDGET_DURATION
